# ตั้งค่า server ต้นทาง (Upstream servers)
upstream web_server {
    # ชื่อ service 'web' และ port ภายใน container ที่กำหนดใน Dockerfile ของ web app
    server web:8000;
}

upstream adminer_server {
    # ชื่อ service 'adminer' และ port พื้นฐานของ adminer
    server adminer:8080;
}


server {
    listen 80;

    # การตั้งค่าสำหรับ proxy ไปยัง Web App
    location / {
        proxy_pass http://web_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # การตั้งค่าสำหรับ proxy ไปยัง Adminer
    # สามารถเข้าถึงได้ผ่าน http://your-domain:10462/adminer/
    location /adminer/ {
        proxy_pass http://adminer_server/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
